version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/food_truck_db
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - app-network
    environment:
      MONGO_INITDB_DATABASE: food_truck_db
    command: ['mongod', '--bind_ip_all']

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
